# Generated by Django 3.1.14 on 2023-01-21 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.IntegerField(blank=True, choices=[(1, 'SUPPLIER'), (2, 'BUYER'), (3, 'GMT VENDOR'), (4, 'RM'), (5, 'RM_ADMIN'), (6, 'PD'), (7, 'PD_ADMIN'), (8, 'VENDOR WITH GARMENTING'), (9, 'Calender_Admin'), (10, 'Planning'), (11, 'Design'), (11, 'Sourcing'), (12, 'Tech'), (13, 'Operations'), (14, 'Finance')], null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_email', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('blocktime', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('reset_password', models.CharField(blank=True, max_length=100, null=True)),
                ('buying_email', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
