# Generated by Django 3.1.14 on 2022-12-02 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='order_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.order_type'),
        ),
    ]
