# Generated by Django 3.1.14 on 2022-12-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_otb'),
    ]

    operations = [
        migrations.AddField(
            model_name='otb',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
