# Generated by Django 3.1.14 on 2022-12-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_assortment_domimp_fabric_type_onoff_wwnww'),
    ]

    operations = [
        migrations.AddField(
            model_name='assortment',
            name='assortment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
