# Generated by Django 3.1.14 on 2022-12-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_assortment_assortment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assortment',
            name='techpack',
            field=models.FileField(default=1991, upload_to='techpack/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
