# Generated by Django 3.1.14 on 2022-12-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_order_management'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_management',
            old_name='options',
            new_name='total_inventory',
        ),
        migrations.RenameField(
            model_name='order_management',
            old_name='quantity',
            new_name='total_return',
        ),
        migrations.RemoveField(
            model_name='order_management',
            name='article_type',
        ),
        migrations.RemoveField(
            model_name='order_management',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='order_management',
            name='content1',
        ),
        migrations.RemoveField(
            model_name='order_management',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='order_management',
            name='content3',
        ),
        migrations.RemoveField(
            model_name='order_management',
            name='domimp',
        ),
        migrations.RemoveField(
            model_name='order_management',
            name='drop',
        ),
        migrations.RemoveField(
            model_name='order_management',
            name='fabric_type',
        ),
        migrations.RemoveField(
            model_name='order_management',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='order_management',
            name='inward_month',
        ),
        migrations.RemoveField(
            model_name='order_management',
            name='onoff',
        ),
        migrations.RemoveField(
            model_name='order_management',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='order_management',
            name='season',
        ),
        migrations.RemoveField(
            model_name='order_management',
            name='wwnww',
        ),
        migrations.AddField(
            model_name='order_management',
            name='total_sale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order_management',
            name='under_production',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
