# Generated by Django 3.1.14 on 2022-12-17 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20221217_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_management',
            name='article_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.article_type'),
        ),
        migrations.AddField(
            model_name='order_management',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.buyer'),
        ),
        migrations.AddField(
            model_name='order_management',
            name='drop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.drop'),
        ),
        migrations.AddField(
            model_name='order_management',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.gender'),
        ),
        migrations.AddField(
            model_name='order_management',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.season'),
        ),
    ]
