# Generated by Django 3.1.14 on 2022-12-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20221217_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_management',
            name='app',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order_management',
            name='asp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
