# Generated by Django 3.1.14 on 2022-12-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20221219_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_management',
            name='app',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='order_management',
            name='asp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
