# Generated by Django 3.1.14 on 2022-12-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20221219_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='otb',
            name='otb_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
