# Generated by Django 3.1.14 on 2023-01-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_otb_otb_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
    ]
