# Generated by Django 3.1.14 on 2023-01-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_department_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
