# Generated by Django 3.1.14 on 2023-05-28 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_department_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='from_city',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='buying_email',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='design_email',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='finance_email',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='fit_email',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='operations_email',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='pd_email',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='planning_email',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='rm_email',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='sourcing_email',
        ),
        migrations.RemoveField(
            model_name='calender',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='department',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='drop',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='otb',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='otb',
            name='otb_balance',
        ),
        migrations.RemoveField(
            model_name='otb',
            name='otb_consumed',
        ),
        migrations.RemoveField(
            model_name='otb',
            name='season',
        ),
        migrations.RemoveField(
            model_name='otb',
            name='total_otb',
        ),
        migrations.RemoveField(
            model_name='season',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='emp_name',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='to_city',
        ),
        migrations.AddField(
            model_name='designation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order_management',
            name='van',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='otb',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assortment',
            name='techpack',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='domimp',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drop',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fabric_type',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='onoff',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_management',
            name='app',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='order_management',
            name='asp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wwnww',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AlterField(
            model_name='assortment',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.brand'),
        ),
        migrations.AlterField(
            model_name='order_management',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.brand'),
        ),
    ]
