# Generated by Django 3.1.14 on 2023-05-28 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20230528_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_management',
            name='article_type',
        ),
        migrations.RemoveField(
            model_name='order_management',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='order_management',
            name='drop',
        ),
        migrations.RemoveField(
            model_name='order_management',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='order_management',
            name='season',
        ),
    ]
