# Generated by Django 3.1.14 on 2023-05-28 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_order_management_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_management',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order_management',
            name='van',
        ),
    ]
