# Generated by Django 3.1.14 on 2023-05-28 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20230528_1118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_management',
        ),
    ]
