# Generated by Django 3.1.14 on 2023-05-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_season_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
