# Generated by Django 3.1.14 on 2023-06-05 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_drop_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='otb',
            name='Article_Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.article_type'),
        ),
        migrations.AddField(
            model_name='otb',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.brand'),
        ),
        migrations.AddField(
            model_name='otb',
            name='drop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.drop'),
        ),
        migrations.AddField(
            model_name='otb',
            name='otb_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otb',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.season'),
        ),
    ]
