# Generated by Django 3.1.14 on 2023-06-05 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20230605_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otb',
            old_name='Article_Type',
            new_name='article_type',
        ),
    ]
