# Generated by Django 3.1.14 on 2023-06-08 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20230605_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assortment',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.buyer'),
        ),
        migrations.AlterField(
            model_name='otb',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.buyer'),
        ),
    ]
